<?php

namespace ComposterBundle\Repository;

/**
 * CompostableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompostableRepository extends \Doctrine\ORM\EntityRepository
{

    public function getQbIsActive()
    {
        $qb = $this->createQueryBuilder('c');

        return $qb->where($qb->expr()->eq('c.actif', ':actif'))
            ->setParameter(':actif', true);
    }

}
